### ISSUE TITLE
Add meta features to declarations.

### ISSUE THREAD

**Issue by terfloth** [Yakindu/statecharts#2465]
Declarations should be extended in a way that declarations can contain declarations. This allows the introduction of meta features that are declared on the meta level like in a domain implementation.

This task must include:

- [x] extension of the types meta model.
- [x] extension of the type inferrer if necessary.
- [x] adding an expression for meta feature calls.
