### ISSUE TITLE
[C++ Generator] Enable -Wall, -Wextra and -Werror on build server for C++

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2513]
- [ ]  Convert string to char* warning #2510 

- [ ] Unused functions in SCTUnit #2509 

- [ ] Remove unused variables from SCTUnit tests #2508 

- [ ] Parantheses around binary operations #2507

- [ ] Unused variables caused by react methods #2467
